name: "Mayhem for Code"
description: "Automatically test your Rust targets with Mayhem"
author: "ForAllSecure"
inputs:
  mayhem-url:
    description: URL pointing to your Mayhem instance
    required: true
  github-token:
    description: github token for posting feedback
    required: false
    default: ${{ github.token }}
  mayhem-token:
    description: Personal API token for authenticating to Mayhem
    required: true
  sarif-output:
    description: SARIF output directory. You can upload to to GitHub using the 'github/codeql-action/upload-sarif@v1' action
    required: false
  args:
    description: command line arguments to override CLI behavior
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "shield"
  color: "red"
